feat: vscode devcontainer configuration
henricm/ha-ferroamp pull request #373
Opened 2023-07-26 20:18 UTC by bj00rn

Add vscode devcontainer configuration.

2023-07-26 20:36 UTC, bj00rn commented
@argoyle not sure why hassfest is complaining, seems to be unlelated to this PR

2023-07-26 20:46 UTC, argoyle commented
New requirements on services perhaps? I'll take a look at the PR tomorrow and see if I can find anything related to those errors.

2023-07-27 08:46 UTC, argoyle requested changes
Just a small typo and an addition of http:// for extra clarity otherwise 💯

2023-07-27 08:46 UTC, argoyle commented on .devcontainer/README.md
> +The devcontainer canbe restarted by opening the command palette and selecting `Tasks: Restart Running Task`, then select the task `Run Home Assistant on port 8123`.
```suggestion
The devcontainer can be restarted by opening the command palette and selecting `Tasks: Restart Running Task`, then select the task `Run Home Assistant on port 8123`.
```

2023-07-27 08:46 UTC, argoyle commented on .devcontainer/README.md
> +When the devcontainer is running, open a browser and navigate to `localhost:8123` and finish configuration of the instance.
```suggestion
When the devcontainer is running, open a browser and navigate to `http://localhost:8123` and finish configuration of the instance.
```

2023-07-27 09:04 UTC, argoyle commented
> @argoyle not sure why hassfest is complaining, seems to be unlelated to this PR

I've added name to the services so just rebase your branch and hassfest should be happy again I think.

2023-07-27 20:15 UTC, bj00rn commented
@argoyle are you using any formatter for this project? black or the likes?

vscode can be quite intrusive with formatting if user settings differ from the code style of the project, unless formatter is set in .vscode/settings.json

2023-07-28 14:24 UTC, argoyle commented
Not at the moment. Far from a Python ninja so not well versed in the ecosystem and best practices. Not against adding it to make it easier to contribute changes without adding mixed code style etc. Let's merge this as is now and add more stuff later.

2023-07-28 14:25 UTC, merged

2023-07-28 23:15 UTC, bj00rn commented
> Not at the moment. Far from a Python ninja so not well versed in the ecosystem and best practices. Not against adding it to make it easier to contribute changes without adding mixed code style etc. Let's merge this as is now and add more stuff later.

Made a PR to enforce codestyle using black and isort. Have a look, the most notable change is double qoutes and line width

2023-07-28 23:31 UTC, bj00rn commented
https://github.com/henricm/ha-ferroamp/pull/375